# Deployment Target
platform :ios, '8.0'

# Ignore pods code warnings
inhibit_all_warnings!

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'KeyboardAvoidingView_Example' do
    pod 'KeyboardAvoidingView', :path => '../'
    
    pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions'

    target 'KeyboardAvoidingView_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
    end
end


post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../podInstall.command"
    pods_project.new_file "../podUpdate.command"
end
